name: 压缩 JS 和 CSS 文件
on:
  push:
    branches: development
jobs:
  Minify:
    runs-on: ubuntu-latest
    steps:
    - name: 读取文件
      uses: actions/checkout@v3
    - name: 压缩 JS 和 CSS 文件
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true
    - name: 提交压缩后的文件
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Github Action] 压缩 JS 和 CSS 文件"
        branch: production
        push_options: "--force"
        skip_checkout: true
